version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  pulsar:
    image: apachepulsar/pulsar-standalone:2.4.2
    ports:
      - 6650:6650
      - 8080:8080
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000
  etcd1:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd1
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 2301:2379
      - 3381:2380
  etcd2:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd2
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 2302:2379
      - 3382:2380
  etcd3:
    image: quay.io/coreos/etcd:v3.4.4
    entrypoint: /usr/local/bin/etcd
    command: >
      --name etcd3
      --initial-advertise-peer-urls http://${HOST}:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://${HOST}:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --log-level=debug
    expose:
      - 2379
      - 2380
    ports:
      - 2303:2379
      - 3383:2380
