name: Build

on:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - name: External Dependencies
        run: docker-compose up -d
      - name: Wait
        run: sleep 15
      - name: Maven Install
        run: mvn install
