name: buildpr

on:
  pull_request:
    branches:
      - master

jobs:
  buildpr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - name: External Dependencies
        run: docker-compose up
      - name: buildpr
        run: |
          mvn install
